### ISSUE TITLE
in 1.8.8, using version 1.0.0, the entire world is just stone

### ISSUE THREAD

**Issue by ooodlllars** [nvx/CleanroomGenerator#24]
everything is stone

**Comment by JHarris12345** [comment]
The wiki doesnt work for 1.8 im having the same issue

**Comment by nvx** [comment]
Can you confirm you really mean Minecraft 1.8 which is over 5 years old? If so version 1.0.0 of this plugin would be the right version to use, but without more details like exactly what your worldgen parameters are and startup logs I can't help beyond that.

Do note that in version v1.0.0 and earlier a comma (`,`) was used as a separator instead of the pipe character (`|`), and the block names were quite different back then too.

**Comment by nvx** [comment]
Closing old issue due to lack of response.
