### ISSUE TITLE
Upgrading world in 1.18.1 breaks the world

### ISSUE THREAD

**Issue by TheNety** [nvx/CleanroomGenerator#30]
Hey, using this generator `CleanroomGenerator:54|stone|4|dirt|1|grass_block`. Purpur 1.18.1, CleanroomGenerator 1.2.1. 

When forceUpgrading the flat world on 1.18.1 (previously was on 1.17.1) the layers 60-63 are just cut out and replaced by air in the whole world. It's the 4 blocks high layer just above the ground (grass_block at the top).

Removing the plugin and then forceUpgrading fixes this issue.

**Comment by nvx** [comment]
That honestly sounds like a bug with the upgrade process. World generators are only designed to be called to create a new unexplored chunk. Existing chunks shouldn't have the world generator called at all for them, be it for an upgrade or other reasons so I'm inclined to think there's a bug with world generators and the upgrade process generally, rather than being an issue specific with CleanroomGenerator.

If you can find any evidence to the contrary that CleanroomGenerator should be doing something different I'd be happy to re-open this issue though.
